export const SUBMIT_REGISTRATION_REQUEST = 'SUBMIT_REGISTRATION_REQUEST';
export const SUBMIT_REGISTRATION_SUCCESS = 'SUBMIT_REGISTRATION_SUCCESS';
export const SUBMIT_REGISTRATION_FAILURE = 'SUBMIT_REGISTRATION_FAILURE';
